### PR TITLE
Update test.c

### PR DESCRIPTION
**Pull request by gccyak2**
Totally money-making feature here!

### CODE REVIEW

**Comment by gccyak2** [comment]
This is my proposed new feature!  You should merge it dude!

**Comment by gccyak1** [comment]
Hey, how will we make big money with this?

**Comment by gccyak2** [comment]
# You gotta be kidding!  It's obvious!  Read the code man!

**Comment by gccyak1** [comment]
Oh sorry, I see it now.  Yes, we will all become rich and world peace will ensue!

**Pull request merged**
